import { ChaveValorDTO } from './../../model/dto/chave-valor.dto';

  export class ListaObjetoUtils {

    public static listaTipoUF(): Array<ChaveValorDTO> {
      let listaTipoUF: Array<ChaveValorDTO> = new Array<ChaveValorDTO>();
      listaTipoUF.push(new ChaveValorDTO('AC', 'Acre'));
      listaTipoUF.push(new ChaveValorDTO('AL', 'Alagoas'));
      listaTipoUF.push(new ChaveValorDTO('AP', 'Amapá'));
      listaTipoUF.push(new ChaveValorDTO('AM', 'Amazonas'));
      listaTipoUF.push(new ChaveValorDTO('BA', 'Bahia'));
      listaTipoUF.push(new ChaveValorDTO('CE', 'Ceará'));
      listaTipoUF.push(new ChaveValorDTO('DF', 'Distrito Federal'));
      listaTipoUF.push(new ChaveValorDTO('ES', 'Espírito Santo'));
      listaTipoUF.push(new ChaveValorDTO('GO', 'Goiás'));
      listaTipoUF.push(new ChaveValorDTO('MA', 'Maranhão'));
      listaTipoUF.push(new ChaveValorDTO('MT', 'Mato Grosso'));
      listaTipoUF.push(new ChaveValorDTO('MS', 'Mato Grosso do Sul'));
      listaTipoUF.push(new ChaveValorDTO('MG', 'Minas Gerais'));
      listaTipoUF.push(new ChaveValorDTO('PA', 'Pará'));
      listaTipoUF.push(new ChaveValorDTO('PB', 'Paraíba'));
      listaTipoUF.push(new ChaveValorDTO('PR', 'Paraná'));
      listaTipoUF.push(new ChaveValorDTO('PE', 'Pernambuco'));
      listaTipoUF.push(new ChaveValorDTO('PI', 'Piauí'));
      listaTipoUF.push(new ChaveValorDTO('RJ', 'Rio de Janeiro'));
      listaTipoUF.push(new ChaveValorDTO('RN', 'Rio Grande do Norte'));
      listaTipoUF.push(new ChaveValorDTO('RS', 'Rio Grande do Sul'));
      listaTipoUF.push(new ChaveValorDTO('RO', 'Rondônia'));
      listaTipoUF.push(new ChaveValorDTO('RR', 'Roraima'));
      listaTipoUF.push(new ChaveValorDTO('SC', 'Santa Catarina'));
      listaTipoUF.push(new ChaveValorDTO('SP', 'São Paulo'));
      listaTipoUF.push(new ChaveValorDTO('SE', 'Sergipe'));
      listaTipoUF.push(new ChaveValorDTO('TO', 'Tocantins'));

      return listaTipoUF;

    }
    
    public static listaBanco(): Array<ChaveValorDTO> {
        let listaBanco: Array<ChaveValorDTO> = new Array<ChaveValorDTO>();
        listaBanco.push(new ChaveValorDTO('001', '001 - BANCO DO BRASIL S/A', 1));
        listaBanco.push(new ChaveValorDTO('002', '002 - BANCO CENTRAL DO BRASIL', 2));
        listaBanco.push(new ChaveValorDTO('003', '003 - BANCO DA AMAZONIA S.A', 3));
        listaBanco.push(new ChaveValorDTO('004', '004 - BANCO DO NORDESTE DO BRASIL S.A', 4));
        listaBanco.push(new ChaveValorDTO('007', '007 - BANCO NAC DESENV. ECO. SOCIAL S.A', 7));
        listaBanco.push(new ChaveValorDTO('008', '008 - BANCO MERIDIONAL DO BRASIL', 8));
        listaBanco.push(new ChaveValorDTO('020', '020 - BANCO DO ESTADO DE ALAGOAS S.A', 20));
        listaBanco.push(new ChaveValorDTO('021', '021 - BANCO DO ESTADO DO ESPIRITO SANTO S.A', 21));
        listaBanco.push(new ChaveValorDTO('022', '022 - BANCO DE CREDITO REAL DE MINAS GERAIS SA', 22));
        listaBanco.push(new ChaveValorDTO('024', '024 - BANCO DO ESTADO DE PERNAMBUCO', 24));
        listaBanco.push(new ChaveValorDTO('025', '025 - BANCO ALFA S/A', 25));
        listaBanco.push(new ChaveValorDTO('026', '026 - BANCO DO ESTADO DO ACRE S.A', 26));
        listaBanco.push(new ChaveValorDTO('027', '027 - BANCO DO ESTADO DE SANTA CATARINA S.A', 27));
        listaBanco.push(new ChaveValorDTO('028', '028 - BANCO DO ESTADO DA BAHIA S.A', 28));
        listaBanco.push(new ChaveValorDTO('029', '029 - BANCO DO ESTADO DO RIO DE JANEIRO S.A', 29));
        listaBanco.push(new ChaveValorDTO('030', '030 - BANCO DO ESTADO DA PARAIBA S.A', 30));
        listaBanco.push(new ChaveValorDTO('031', '031 - BANCO DO ESTADO DE GOIAS S.A', 31));
        listaBanco.push(new ChaveValorDTO('032', '032 - BANCO DO ESTADO DO MATO GROSSO S.A.', 32));
        listaBanco.push(new ChaveValorDTO('033', '033 - BANCO DO ESTADO DE SAO PAULO S.A', 33));
        listaBanco.push(new ChaveValorDTO('034', '034 - BANCO DO ESADO DO AMAZONAS S.A', 34));
        listaBanco.push(new ChaveValorDTO('035', '035 - BANCO DO ESTADO DO CEARA S.A', 35));
        listaBanco.push(new ChaveValorDTO('036', '036 - BANCO DO ESTADO DO MARANHAO S.A', 36));
        listaBanco.push(new ChaveValorDTO('037', '037 - BANCO DO ESTADO DO PARA S.A', 37));
        listaBanco.push(new ChaveValorDTO('038', '038 - BANCO DO ESTADO DO PARANA S.A', 38));
        listaBanco.push(new ChaveValorDTO('039', '039 - BANCO DO ESTADO DO PIAUI S.A', 39));
        listaBanco.push(new ChaveValorDTO('041', '041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A', 41));
        listaBanco.push(new ChaveValorDTO('047', '047 - BANCO DO ESTADO DE SERGIPE S.A', 47));
        listaBanco.push(new ChaveValorDTO('048', '048 - BANCO DO ESTADO DE MINAS GERAIS S.A', 48));
        listaBanco.push(new ChaveValorDTO('059', '059 - BANCO DO ESTADO DE RONDONIA S.A', 59));
        listaBanco.push(new ChaveValorDTO('070', '070 - BANCO DE BRASILIA S.A', 70));
        listaBanco.push(new ChaveValorDTO('104', '104 - CAIXA ECONOMICA FEDERAL', 104));
        listaBanco.push(new ChaveValorDTO('106', '106 - BANCO ITABANCO S.A.', 106));
        listaBanco.push(new ChaveValorDTO('107', '107 - BANCO BBM S.A', 107));
        listaBanco.push(new ChaveValorDTO('109', '109 - BANCO CREDIBANCO S.A', 109));
        listaBanco.push(new ChaveValorDTO('116', '116 - BANCO B.N.L DO BRASIL S.A', 116));
        listaBanco.push(new ChaveValorDTO('148', '148 - MULTI BANCO S.A', 148));
        listaBanco.push(new ChaveValorDTO('151', '151 - CAIXA ECONOMICA DO ESTADO DE SAO PAULO', 151));
        listaBanco.push(new ChaveValorDTO('153', '153 - CAIXA ECONOMICA DO ESTADO DO R.G.SUL', 153));
        listaBanco.push(new ChaveValorDTO('165', '165 - BANCO NORCHEM S.A', 165));
        listaBanco.push(new ChaveValorDTO('166', '166 - BANCO INTER-ATLANTICO S.A', 166));
        listaBanco.push(new ChaveValorDTO('168', '168 - BANCO C.C.F. BRASIL S.A', 168));
        listaBanco.push(new ChaveValorDTO('175', '175 - CONTINENTAL BANCO S.A', 175));
        listaBanco.push(new ChaveValorDTO('184', '184 - BBA - CREDITANSTALT S.A', 184));
        listaBanco.push(new ChaveValorDTO('199', '199 - BANCO FINANCIAL PORTUGUES', 199));
        listaBanco.push(new ChaveValorDTO('200', '200 - BANCO FRICRISA AXELRUD S.A', 200));
        listaBanco.push(new ChaveValorDTO('201', '201 - BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A', 201));
        listaBanco.push(new ChaveValorDTO('204', '204 - BANCO S.R.L S.A', 204));
        listaBanco.push(new ChaveValorDTO('205', '205 - BANCO SUL AMERICA S.A', 205));
        listaBanco.push(new ChaveValorDTO('206', '206 - BANCO MARTINELLI S.A', 206));
        listaBanco.push(new ChaveValorDTO('208', '208 - BANCO PACTUAL S.A', 208));
        listaBanco.push(new ChaveValorDTO('210', '210 - DEUTSCH SUDAMERIKANICHE BANK AG', 210));
        listaBanco.push(new ChaveValorDTO('211', '211 - BANCO SISTEMA S.A', 211));
        listaBanco.push(new ChaveValorDTO('212', '212 - BANCO MATONE S.A', 212));
        listaBanco.push(new ChaveValorDTO('213', '213 - BANCO ARBI S.A', 213));
        listaBanco.push(new ChaveValorDTO('214', '214 - BANCO DIBENS S.A', 214));
        listaBanco.push(new ChaveValorDTO('215', '215 - BANCO AMERICA DO SUL S.A', 215));
        listaBanco.push(new ChaveValorDTO('216', '216 - BANCO REGIONAL MALCON S.A', 216));
        listaBanco.push(new ChaveValorDTO('217', '217 - BANCO AGROINVEST S.A', 217));
        listaBanco.push(new ChaveValorDTO('218', '218 - BBS - BANCO BONSUCESSO S.A.', 218));
        listaBanco.push(new ChaveValorDTO('219', '219 - BANCO DE CREDITO DE SAO PAULO S.A', 219));
        listaBanco.push(new ChaveValorDTO('220', '220 - BANCO CREFISUL', 220));
        listaBanco.push(new ChaveValorDTO('221', '221 - BANCO GRAPHUS S.A', 221));
        listaBanco.push(new ChaveValorDTO('222', '222 - BANCO AGF BRASIL S. A.', 222));
        listaBanco.push(new ChaveValorDTO('223', '223 - BANCO INTERUNION S.A', 223));
        listaBanco.push(new ChaveValorDTO('224', '224 - BANCO FIBRA S.A', 224));
        listaBanco.push(new ChaveValorDTO('225', '225 - BANCO BRASCAN S.A', 225));
        listaBanco.push(new ChaveValorDTO('228', '228 - BANCO ICATU S.A', 228));
        listaBanco.push(new ChaveValorDTO('229', '229 - BANCO CRUZEIRO S.A', 229));
        listaBanco.push(new ChaveValorDTO('230', '230 - BANCO BANDEIRANTES S.A', 230));
        listaBanco.push(new ChaveValorDTO('231', '231 - BANCO BOAVISTA S.A', 231));
        listaBanco.push(new ChaveValorDTO('232', '232 - BANCO INTERPART S.A', 232));
        listaBanco.push(new ChaveValorDTO('233', '233 - BANCO MAPPIN S.A', 233));
        listaBanco.push(new ChaveValorDTO('234', '234 - BANCO LAVRA S.A.', 234));
        listaBanco.push(new ChaveValorDTO('235', '235 - BANCO LIBERAL S.A', 235));
        listaBanco.push(new ChaveValorDTO('236', '236 - BANCO CAMBIAL S.A', 236));
        listaBanco.push(new ChaveValorDTO('237', '237 - BANCO BRADESCO S.A', 237));
        listaBanco.push(new ChaveValorDTO('239', '239 - BANCO BANCRED S.A', 239));
        listaBanco.push(new ChaveValorDTO('240', '240 - BANCO DE CREDITO REAL DE MINAS GERAIS S.', 240));
        listaBanco.push(new ChaveValorDTO('241', '241 - BANCO CLASSICO S.A', 241));
        listaBanco.push(new ChaveValorDTO('242', '242 - BANCO EUROINVEST S.A', 242));
        listaBanco.push(new ChaveValorDTO('243', '243 - BANCO STOCK S.A', 243));
        listaBanco.push(new ChaveValorDTO('244', '244 - BANCO CIDADE S.A', 244));
        listaBanco.push(new ChaveValorDTO('245', '245 - BANCO EMPRESARIAL S.A', 245));
        listaBanco.push(new ChaveValorDTO('246', '246 - BANCO ABC ROMA S.A', 246));
        listaBanco.push(new ChaveValorDTO('247', '247 - BANCO OMEGA S.A', 247));
        listaBanco.push(new ChaveValorDTO('249', '249 - BANCO INVESTCRED S.A', 249));
        listaBanco.push(new ChaveValorDTO('250', '250 - BANCO SCHAHIN CURY S.A', 250));
        listaBanco.push(new ChaveValorDTO('251', '251 - BANCO SAO JORGE S.A.', 251));
        listaBanco.push(new ChaveValorDTO('252', '252 - BANCO FININVEST S.A', 252));
        listaBanco.push(new ChaveValorDTO('254', '254 - BANCO PARANA BANCO S.A', 254));
        listaBanco.push(new ChaveValorDTO('255', '255 - MILBANCO S.A.', 255));
        listaBanco.push(new ChaveValorDTO('256', '256 - BANCO GULVINVEST S.A', 256));
        listaBanco.push(new ChaveValorDTO('258', '258 - BANCO INDUSCRED S.A', 258));
        listaBanco.push(new ChaveValorDTO('261', '261 - BANCO VARIG S.A', 261));
        listaBanco.push(new ChaveValorDTO('262', '262 - BANCO BOREAL S.A', 262));
        listaBanco.push(new ChaveValorDTO('263', '263 - BANCO CACIQUE', 263));
        listaBanco.push(new ChaveValorDTO('264', '264 - BANCO PERFORMANCE S.A', 264));
        listaBanco.push(new ChaveValorDTO('265', '265 - BANCO FATOR S.A', 265));
        listaBanco.push(new ChaveValorDTO('266', '266 - BANCO CEDULA S.A', 266));
        listaBanco.push(new ChaveValorDTO('267', '267 - BANCO BBM-COM.C.IMOB.CFI S.A.', 267));
        listaBanco.push(new ChaveValorDTO('275', '275 - BANCO REAL S.A', 275));
        listaBanco.push(new ChaveValorDTO('277', '277 - BANCO PLANIBANC S.A', 277));
        listaBanco.push(new ChaveValorDTO('282', '282 - BANCO BRASILEIRO COMERCIAL', 282));
        listaBanco.push(new ChaveValorDTO('291', '291 - BANCO DE CREDITO NACIONAL S.A', 291));
        listaBanco.push(new ChaveValorDTO('294', '294 - BCR - BANCO DE CREDITO REAL S.A', 294));
        listaBanco.push(new ChaveValorDTO('295', '295 - BANCO CREDIPLAN S.A', 295));
        listaBanco.push(new ChaveValorDTO('300', '300 - BANCO DE LA NACION ARGENTINA S.A', 300));
        listaBanco.push(new ChaveValorDTO('302', '302 - BANCO DO PROGRESSO S.A', 302));
        listaBanco.push(new ChaveValorDTO('303', '303 - BANCO HNF S.A.', 303));
        listaBanco.push(new ChaveValorDTO('304', '304 - BANCO PONTUAL S.A', 304));
        listaBanco.push(new ChaveValorDTO('308', '308 - BANCO COMERCIAL BANCESA S.A.', 308));
        listaBanco.push(new ChaveValorDTO('318', '318 - BANCO B.M.G. S.A', 318));
        listaBanco.push(new ChaveValorDTO('320', '320 - BANCO INDUSTRIAL E COMERCIAL', 320));
        listaBanco.push(new ChaveValorDTO('341', '341 - BANCO ITAU S.A', 341));
        listaBanco.push(new ChaveValorDTO('346', '346 - BANCO FRANCES E BRASILEIRO S.A', 346));
        listaBanco.push(new ChaveValorDTO('347', '347 - BANCO SUDAMERIS BRASIL S.A', 347));
        listaBanco.push(new ChaveValorDTO('351', '351 - BANCO BOZANO SIMONSEN S.A', 351));
        listaBanco.push(new ChaveValorDTO('353', '353 - BANCO GERAL DO COMERCIO S.A', 353));
        listaBanco.push(new ChaveValorDTO('356', '356 - ABN AMRO S.A', 356));
        listaBanco.push(new ChaveValorDTO('366', '366 - BANCO SOGERAL S.A', 366));
        listaBanco.push(new ChaveValorDTO('369', '369 - PONTUAL', 369));
        listaBanco.push(new ChaveValorDTO('370', '370 - BEAL - BANCO EUROPEU PARA AMERICA LATINA', 370));
        listaBanco.push(new ChaveValorDTO('372', '372 - BANCO ITAMARATI S.A', 372));
        listaBanco.push(new ChaveValorDTO('375', '375 - BANCO FENICIA S.A', 375));
        listaBanco.push(new ChaveValorDTO('376', '376 - CHASE MANHATTAN BANK S.A', 376));
        listaBanco.push(new ChaveValorDTO('388', '388 - BANCO MERCANTIL DE DESCONTOS S/A', 388));
        listaBanco.push(new ChaveValorDTO('389', '389 - BANCO MERCANTIL DO BRASIL S.A', 389));
        listaBanco.push(new ChaveValorDTO('392', '392 - BANCO MERCANTIL DE SAO PAULO S.A', 392));
        listaBanco.push(new ChaveValorDTO('394', '394 - BANCO B.M.C. S.A', 394));
        listaBanco.push(new ChaveValorDTO('399', '399 - BANCO BAMERINDUS DO BRASIL S.A', 399));
        listaBanco.push(new ChaveValorDTO('409', '409 - UNIBANCO - UNIAO DOS BANCOS BRASILEIROS', 409));
        listaBanco.push(new ChaveValorDTO('412', '412 - BANCO NACIONAL DA BAHIA S.A', 412));
        listaBanco.push(new ChaveValorDTO('415', '415 - BANCO NACIONAL S.A', 415));
        listaBanco.push(new ChaveValorDTO('420', '420 - BANCO NACIONAL DO NORTE S.A', 420));
        listaBanco.push(new ChaveValorDTO('422', '422 - BANCO SAFRA S.A', 422));
        listaBanco.push(new ChaveValorDTO('424', '424 - BANCO NOROESTE S.A', 424));
        listaBanco.push(new ChaveValorDTO('434', '434 - BANCO FORTALEZA S.A', 434));
        listaBanco.push(new ChaveValorDTO('453', '453 - BANCO RURAL S.A', 453));
        listaBanco.push(new ChaveValorDTO('456', '456 - BANCO TOKIO S.A', 456));
        listaBanco.push(new ChaveValorDTO('464', '464 - BANCO SUMITOMO BRASILEIRO S.A', 464));
        listaBanco.push(new ChaveValorDTO('466', '466 - BANCO MITSUBISHI BRASILEIRO S.A', 466));
        listaBanco.push(new ChaveValorDTO('472', '472 - LLOYDS BANK PLC', 472));
        listaBanco.push(new ChaveValorDTO('473', '473 - BANCO FINANCIAL PORTUGUES S.A', 473));
        listaBanco.push(new ChaveValorDTO('477', '477 - CITIBANK N.A', 477));
        listaBanco.push(new ChaveValorDTO('479', '479 - BANCO DE BOSTON S.A', 479));
        listaBanco.push(new ChaveValorDTO('480', '480 - BANCO PORTUGUES DO ATLANTICO-BRASIL S.A', 480));
        listaBanco.push(new ChaveValorDTO('483', '483 - BANCO AGRIMISA S.A.', 483));
        listaBanco.push(new ChaveValorDTO('487', '487 - DEUTSCHE BANK S.A - BANCO ALEMAO', 487));
        listaBanco.push(new ChaveValorDTO('488', '488 - BANCO J. P. MORGAN S.A', 488));
        listaBanco.push(new ChaveValorDTO('489', '489 - BANESTO BANCO URUGAUAY S.A', 489));
        listaBanco.push(new ChaveValorDTO('492', '492 - INTERNATIONALE NEDERLANDEN BANK N.V.', 492));
        listaBanco.push(new ChaveValorDTO('493', '493 - BANCO UNION S.A.C.A', 493));
        listaBanco.push(new ChaveValorDTO('494', '494 - BANCO LA REP. ORIENTAL DEL URUGUAY', 494));
        listaBanco.push(new ChaveValorDTO('495', '495 - BANCO LA PROVINCIA DE BUENOS AIRES', 495));
        listaBanco.push(new ChaveValorDTO('496', '496 - BANCO EXTERIOR DE ESPANA S.A', 496));
        listaBanco.push(new ChaveValorDTO('498', '498 - CENTRO HISPANO BANCO', 498));
        listaBanco.push(new ChaveValorDTO('499', '499 - BANCO IOCHPE S.A', 499));
        listaBanco.push(new ChaveValorDTO('501', '501 - BANCO BRASILEIRO IRAQUIANO S.A.', 501));
        listaBanco.push(new ChaveValorDTO('502', '502 - BANCO SANTANDER S.A', 502));
        listaBanco.push(new ChaveValorDTO('504', '504 - BANCO MULTIPLIC S.A', 504));
        listaBanco.push(new ChaveValorDTO('505', '505 - BANCO GARANTIA S.A', 505));
        listaBanco.push(new ChaveValorDTO('600', '600 - BANCO LUSO BRASILEIRO S.A', 600));
        listaBanco.push(new ChaveValorDTO('601', '601 - BFC BANCO S.A.', 601));
        listaBanco.push(new ChaveValorDTO('602', '602 - BANCO PATENTE S.A', 602));
        listaBanco.push(new ChaveValorDTO('604', '604 - BANCO INDUSTRIAL DO BRASIL S.A', 604));
        listaBanco.push(new ChaveValorDTO('607', '607 - BANCO SANTOS NEVES S.A', 607));
        listaBanco.push(new ChaveValorDTO('608', '608 - BANCO OPEN S.A', 608));
        listaBanco.push(new ChaveValorDTO('610', '610 - BANCO V.R. S.A', 610));
        listaBanco.push(new ChaveValorDTO('611', '611 - BANCO PAULISTA S.A', 611));
        listaBanco.push(new ChaveValorDTO('612', '612 - BANCO GUANABARA S.A', 612));
        listaBanco.push(new ChaveValorDTO('613', '613 - BANCO PECUNIA S.A', 613));
        listaBanco.push(new ChaveValorDTO('616', '616 - BANCO INTERPACIFICO S.A', 616));
        listaBanco.push(new ChaveValorDTO('617', '617 - BANCO INVESTOR S.A.', 617));
        listaBanco.push(new ChaveValorDTO('618', '618 - BANCO TENDENCIA S.A', 618));
        listaBanco.push(new ChaveValorDTO('621', '621 - BANCO APLICAP S.A.', 621));
        listaBanco.push(new ChaveValorDTO('622', '622 - BANCO DRACMA S.A', 622));
        listaBanco.push(new ChaveValorDTO('623', '623 - BANCO PANAMERICANO S.A', 623));
        listaBanco.push(new ChaveValorDTO('624', '624 - BANCO GENERAL MOTORS S.A', 624));
        listaBanco.push(new ChaveValorDTO('625', '625 - BANCO ARAUCARIA S.A', 625));
        listaBanco.push(new ChaveValorDTO('626', '626 - BANCO FICSA S.A', 626));
        listaBanco.push(new ChaveValorDTO('627', '627 - BANCO DESTAK S.A', 627));
        listaBanco.push(new ChaveValorDTO('628', '628 - BANCO CRITERIUM S.A', 628));
        listaBanco.push(new ChaveValorDTO('629', '629 - BANCORP BANCO COML. E. DE INVESTMENTO', 629));
        listaBanco.push(new ChaveValorDTO('630', '630 - BANCO INTERCAP S.A', 630));
        listaBanco.push(new ChaveValorDTO('633', '633 - BANCO REDIMENTO S.A', 633));
        listaBanco.push(new ChaveValorDTO('634', '634 - BANCO TRIANGULO S.A', 634));
        listaBanco.push(new ChaveValorDTO('635', '635 - BANCO DO ESTADO DO AMAPA S.A', 635));
        listaBanco.push(new ChaveValorDTO('637', '637 - BANCO SOFISA S.A', 637));
        listaBanco.push(new ChaveValorDTO('638', '638 - BANCO PROSPER S.A', 638));
        listaBanco.push(new ChaveValorDTO('639', '639 - BIG S.A. - BANCO IRMAOS GUIMARAES', 639));
        listaBanco.push(new ChaveValorDTO('640', '640 - BANCO DE CREDITO METROPOLITANO S.A', 640));
        listaBanco.push(new ChaveValorDTO('641', '641 - BANCO EXCEL ECONOMICO S/A', 641));
        listaBanco.push(new ChaveValorDTO('643', '643 - BANCO SEGMENTO S.A', 643));
        listaBanco.push(new ChaveValorDTO('645', '645 - BANCO DO ESTADO DE RORAIMA S.A', 645));
        listaBanco.push(new ChaveValorDTO('647', '647 - BANCO MARKA S.A', 647));
        listaBanco.push(new ChaveValorDTO('648', '648 - BANCO ATLANTIS S.A', 648));
        listaBanco.push(new ChaveValorDTO('649', '649 - BANCO DIMENSAO S.A', 649));
        listaBanco.push(new ChaveValorDTO('650', '650 - BANCO PEBB S.A', 650));
        listaBanco.push(new ChaveValorDTO('652', '652 - BANCO FRANCES E BRASILEIRO SA', 652));
        listaBanco.push(new ChaveValorDTO('653', '653 - BANCO INDUSVAL S.A', 653));
        listaBanco.push(new ChaveValorDTO('654', '654 - BANCO A. J. RENNER S.A', 654));
        listaBanco.push(new ChaveValorDTO('655', '655 - BANCO VOTORANTIM S.A.', 655));
        listaBanco.push(new ChaveValorDTO('656', '656 - BANCO MATRIX S.A', 656));
        listaBanco.push(new ChaveValorDTO('657', '657 - BANCO TECNICORP S.A', 657));
        listaBanco.push(new ChaveValorDTO('658', '658 - BANCO PORTO REAL S.A', 658));
        listaBanco.push(new ChaveValorDTO('702', '702 - BANCO SANTOS S.A', 702));
        listaBanco.push(new ChaveValorDTO('705', '705 - BANCO INVESTCORP S.A.', 705));
        listaBanco.push(new ChaveValorDTO('707', '707 - BANCO DAYCOVAL S.A', 707));
        listaBanco.push(new ChaveValorDTO('711', '711 - BANCO VETOR S.A.', 711));
        listaBanco.push(new ChaveValorDTO('713', '713 - BANCO CINDAM S.A', 713));
        listaBanco.push(new ChaveValorDTO('715', '715 - BANCO VEGA S.A', 715));
        listaBanco.push(new ChaveValorDTO('718', '718 - BANCO OPERADOR S.A', 718));
        listaBanco.push(new ChaveValorDTO('719', '719 - BANCO PRIMUS S.A', 719));
        listaBanco.push(new ChaveValorDTO('720', '720 - BANCO MAXINVEST S.A', 720));
        listaBanco.push(new ChaveValorDTO('721', '721 - BANCO CREDIBEL S.A', 721));
        listaBanco.push(new ChaveValorDTO('722', '722 - BANCO INTERIOR DE SAO PAULO S.A', 722));
        listaBanco.push(new ChaveValorDTO('724', '724 - BANCO PORTO SEGURO S.A', 724));
        listaBanco.push(new ChaveValorDTO('725', '725 - BANCO FINABANCO S.A', 725));
        listaBanco.push(new ChaveValorDTO('726', '726 - BANCO UNIVERSAL S.A', 726));
        listaBanco.push(new ChaveValorDTO('728', '728 - BANCO FITAL S.A', 728));
        listaBanco.push(new ChaveValorDTO('729', '729 - BANCO FONTE S.A', 729));
        listaBanco.push(new ChaveValorDTO('730', '730 - BANCO COMERCIAL PARAGUAYO S.A', 730));
        listaBanco.push(new ChaveValorDTO('731', '731 - BANCO GNPP S.A.', 731));
        listaBanco.push(new ChaveValorDTO('732', '732 - BANCO PREMIER S.A.', 732));
        listaBanco.push(new ChaveValorDTO('733', '733 - BANCO NACOES S.A.', 733));
        listaBanco.push(new ChaveValorDTO('734', '734 - BANCO GERDAU S.A', 734));
        listaBanco.push(new ChaveValorDTO('735', '735 - BACO POTENCIAL', 735));
        listaBanco.push(new ChaveValorDTO('736', '736 - BANCO UNITED S.A', 736));
        listaBanco.push(new ChaveValorDTO('737', '737 - THECA', 737));
        listaBanco.push(new ChaveValorDTO('738', '738 - MARADA', 738));
        listaBanco.push(new ChaveValorDTO('739', '739 - BGN', 739));
        listaBanco.push(new ChaveValorDTO('740', '740 - BCN BARCLAYS', 740));
        listaBanco.push(new ChaveValorDTO('741', '741 - BRP', 741));
        listaBanco.push(new ChaveValorDTO('742', '742 - EQUATORIAL', 742));
        listaBanco.push(new ChaveValorDTO('743', '743 - BANCO EMBLEMA S.A', 743));
        listaBanco.push(new ChaveValorDTO('744', '744 - THE FIRST NATIONAL BANK OF BOSTON', 744));
        listaBanco.push(new ChaveValorDTO('745', '745 - CITIBAN N.A.', 745));
        listaBanco.push(new ChaveValorDTO('746', '746 - MODAL SA', 746));
        listaBanco.push(new ChaveValorDTO('747', '747 - RAIBOBANK DO BRASIL', 747));
        listaBanco.push(new ChaveValorDTO('748', '748 - SICREDI', 748));
        listaBanco.push(new ChaveValorDTO('749', '749 - BRMSANTIL SA', 749));
        listaBanco.push(new ChaveValorDTO('750', '750 - BANCO REPUBLIC NATIONAL OF NEW YORK (BRA', 750));
        listaBanco.push(new ChaveValorDTO('751', '751 - DRESDNER BANK LATEINAMERIKA-BRASIL S/A', 751));
        listaBanco.push(new ChaveValorDTO('752', '752 - BANCO BANQUE NATIONALE DE PARIS BRASIL S', 752));
        listaBanco.push(new ChaveValorDTO('753', '753 - BANCO COMERCIAL URUGUAI S.A.', 753));
        listaBanco.push(new ChaveValorDTO('755', '755 - BANCO MERRILL LYNCH S.A', 755));
        listaBanco.push(new ChaveValorDTO('756', '756 - BANCO COOPERATIVO DO BRASIL S.A.', 756));
        listaBanco.push(new ChaveValorDTO('757', '757 - BANCO KEB DO BRASIL S.A.', 757));

        return listaBanco;
  }

}